name: Beeline-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt install openjdk-8-jre maven docker docker-compose
    - name: Grant execute permission for run.sh script
      run: chmod +x run.sh
    - name: Build the project
      run: ./run.sh
    - name: Setup Python  
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        token: b1d12e18-74cd-44c8-8b0d-69bda521b6f6
        file: ./coverage.xml
        flags: unittests
        name: codecov-beeline
        fail_ci_if_error: true 
