name: Beeline-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt install openjdk-8-jre maven docker docker-compose
    - name: Grant execute permission for run.sh script
      run: chmod +x run.sh
    - name: Build the project
      run: ./run.sh
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
