name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt install openjdk-8-jre maven docker docker-compose
    - name: Grant execute permission for run.sh script
      run: chmod +x run.sh
    - name: Build the project
      run: ./run.sh
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash) -t b1d12e18-74cd-44c8-8b0d-69bda521b6f6
